{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "luckygo.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "luckygo.backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "luckygo.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "luckygo.backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "luckygo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.backend.image.registry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "luckygo.fullname" . }}-config
            - secretRef:
                name: {{ include "luckygo.fullname" . }}-secret
          {{- if .Values.backend.healthCheck.enabled }}
          livenessProbe:
            {{- toYaml .Values.backend.healthCheck.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.healthCheck.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: logs-volume
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
            {{- if .Values.sqlite.enabled }}
            {{- if .Values.sqlite.persistence.enabled }}
            - name: sqlite-data-volume
              mountPath: {{ .Values.sqlite.persistence.mountPath }}
            {{- end }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: logs-volume
          persistentVolumeClaim:
            claimName: {{ include "luckygo.fullname" . }}-logs-pvc
        {{- end }}
        {{- if .Values.sqlite.enabled }}
        {{- if .Values.sqlite.persistence.enabled }}
        - name: sqlite-data-volume
          persistentVolumeClaim:
            claimName: {{ include "luckygo.fullname" . }}-sqlite-pvc
        {{- end }}
        {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
