{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "luckygo.fullname" . }}-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "luckygo.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "luckygo.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- if has "Ingress" .Values.networkPolicy.policyTypes }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - podSelector:
            matchLabels:
              {{- include "luckygo.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.frontend.service.targetPort }}
        - protocol: TCP
          port: {{ .Values.backend.service.targetPort }}
    - from:
        - podSelector:
            matchLabels:
              {{- include "luckygo.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.backend.service.targetPort }}
  {{- end }}
  {{- if has "Egress" .Values.networkPolicy.policyTypes }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "luckygo.selectorLabels" . | nindent 14 }}
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
    - to: []
      ports:
        - protocol: TCP
          port: 6379  # Redis
        - protocol: TCP
          port: 53    # DNS
        - protocol: UDP
          port: 53    # DNS
  {{- end }}
{{- end }}
