{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "luckygo.fullname" . }}-logs-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "luckygo.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}

---

{{- if .Values.sqlite.enabled }}
{{- if .Values.sqlite.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "luckygo.fullname" . }}-sqlite-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "luckygo.labels" . | nindent 4 }}
    app.kubernetes.io/component: sqlite-storage
spec:
  accessModes:
    - {{ .Values.sqlite.persistence.accessMode }}
  {{- if .Values.sqlite.persistence.storageClass }}
  {{- if (eq "-" .Values.sqlite.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.sqlite.persistence.storageClass }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sqlite.persistence.size }}
{{- end }}
{{- end }}
