{{- if and .Values.redis.enabled .Values.redisUI.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "luckygo.fullname" . }}-redis-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "luckygo.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis-ui
spec:
  type: {{ .Values.redisUI.service.type }}
  ports:
    - port: {{ .Values.redisUI.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "luckygo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis-ui
{{- end }}
