{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "luckygo.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "luckygo.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "luckygo.frontend.selectorLabels" . | nindent 4 }}
---
{{- end }}
{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "luckygo.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "luckygo.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "luckygo.backend.selectorLabels" . | nindent 4 }}
{{- end }}
